---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-nginx
data:
  index.properties: |
    <html>
      <head>
        <title>Netology</title>
      </head>
      <body>
        <p><strong>VERSION 1</strong></p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          volumeMounts:
          - name: config
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-for-nginx
          items:
          - key: "index.properties"
            path: "index.html"
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec:
 selector:
   app: nginx
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: public
  rules:
  - http:
     paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v2
  labels:
    app: nginx-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-v2
  template:
    metadata:
      labels:
        app: nginx-v2
    spec:
      containers:
        - name: nginx-v2
          image: nginx:latest
          volumeMounts:
          - name: config
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-for-nginx-canary
          items:
          - key: "index.properties"
            path: "index.html"
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-v2-svc
spec:
 selector:
   app: nginx-v2
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-nginx-canary
data:
  index.properties: |
    <html>
      <head>
        <title>Netology</title>
      </head>
      <body>
        <p><strong>VERSION 2</strong></p>
      </body>
    </html>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-v2
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  ingressClassName: public
  rules:
  - http:
     paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-v2-svc
            port:
              number: 80
---