---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-dep
  labels:
    app: multitool-dep
spec:
  replicas: 5
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 75%
      maxSurge: 2
  selector:
    matchLabels:
      app: multitool-dep
  template:
    metadata:
      labels:
        app: multitool-dep
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        ports:
        - containerPort: 1180
          name: multitool-port
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: nginx-port
---
apiVersion: v1
kind: Service
metadata: 
  name: multitool-svc
spec:
  selector:
    app: multitool-dep
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: nginx-port
    - name: multitool-port
      protocol: TCP
      port: 81
      targetPort: multitool-port