---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-local
  local:
    path: /mnt/share/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - workernode
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: sc-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-dep
  labels:
    app: pvc-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-dep
  template:
    metadata:
      labels:
        app: pvc-dep
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command: ['sh', '-c', "while(true); do echo 'new log'>>/mnt/share/log1.txt; sleep 5; done"]
          volumeMounts:
          - mountPath: /mnt/share
            name: share
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /mnt/share      
            name: share
      volumes:
      - name: share
        persistentVolumeClaim:
          claimName: pvc-local
