---
apiVersion: v1
kind: Service
metadata: 
  name: multitool-svc
spec:
  selector:
    app: multitool-dep
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: nginx-port
    - name: multitool-port
      protocol: TCP
      port: 81
      targetPort: multitool-port
