---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-dep
  labels:
    app: multitool-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-dep
  template:
    metadata:
      labels:
        app: multitool-dep
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        ports:
        - containerPort: 1180
          name: multitool-port
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-port
