apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {}
    http {
     log_format  main  'Remote addres: $remote_addr\n'
                      'Remote user: $remote_user\n'
                      'Time local: $time_local\n'
                      'Request: $request\n'
                      'Status code: $status\n'
                      'Byte body: $body_bytes_sent\n'
                      'Referer: $http_Referer\n'
                      'User Agent: $http_User_Agent\n'
                      'X-Forwarded-For: $http_X_Forwarded_For\n'
                      'ConnectionID: $connection\n'
                      'Request lenth: $request_length\n'
                      'Request time: $request_time\n'
                      'URL: $uri\n'
                      'ClientId: $http_ClientId\n';
    
    server {
      listen 80 default_server;
          
      location / {
          proxy_pass http://multitool;
          proxy_set_header Host $host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection keep-alive;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
    upstream multitool {
       zone multitool 64k;
       server 127.0.0.1:1180;
    }
    }
